blog: atlas-migrate-status

diff --git a/contents-manager/Makefile b/contents-manager/Makefile
--- a/contents-manager/Makefile
+++ b/contents-manager/Makefile
@@ -11,10 +11,27 @@ IMAGE_NAME    := asia-northeast1-docker.pkg.dev/$(GCP_PROJECT)/$(AR_REPOSITORY)/
 
 SERVICE_NAME := $(APP_NAME)
 
+ARTICLE_TEMPLATE := _article_template.md
+
 include ../infrastructure/docker.mk
 
 # deploy: .check-env
 # 	gcloud run deploy $
+
+.PHONY: new-article
+new-article:
+ifndef name
+	$(error name is required: make new-article name=my-article)
+endif
+	@filename=$(name); \
+	case $$filename in *.md) ;; *) filename="$$filename.md" ;; esac; \
+	filepath=articles/$$filename; \
+	if [ ! -f $(ARTICLE_TEMPLATE) ]; then echo "Error: template '$(ARTICLE_TEMPLATE)' not found"; exit 1; fi; \
+	if [ -e $$filepath ]; then echo "Error: $$filepath already exists"; exit 1; fi; \
+	today=$$(date +%Y-%m-%d); \
+	title=$${filename%.md}; \
+	sed -e "s/__TITLE__/$$title/g" -e "s/__DATE__/$$today/g" $(ARTICLE_TEMPLATE) > $$filepath; \
+	echo "Created $$filepath"
 
 build-and-push: .check-env build-image push-image
 
@@ -22,4 +39,3 @@ build-and-push: .check-env build-image push-image
 ifndef ENV
 	$(error ENV is required.)
 endif
-
